`{` missing error fix
Error fixed {mirmohmmadluqman@Lenovo-ThinkPad-P1:/mnt/c/Users/Mir Mohmmad Luqman/Documents/Turbin 3/Number-Oracle$ cargo run
   Compiling Number-Oracle v0.1.0 (/mnt/c/Users/Mir Mohmmad Luqman/Documents/Turbin 3/Number-Oracle)
error: unexpected closing delimiter: `}`
  --> src/main.rs:36:1
   |
11 |     loop {
   |          - this opening brace...
...
35 |     }
   |     - ...matches this closing brace
36 | }
   | ^ unexpected closing delimiter

error: could not compile `Number-Oracle` (bin "Number-Oracle") due to 1 previous error}
---
Compilation Success{
mirmohmmadluqman@Lenovo-ThinkPad-P1:/mnt/c/Users/Mir Mohmmad Luqman/Documents/Turbin 3/Number-Oracle$ cargo run
   Compiling Number-Oracle v0.1.0 (/mnt/c/Users/Mir Mohmmad Luqman/Documents/Turbin 3/Number-Oracle)
error: unexpected closing delimiter: `}`
  --> src/main.rs:36:1
   |
11 |     loop {
   |          - this opening brace...
...
35 |     }
   |     - ...matches this closing brace
36 | }
   | ^ unexpected closing delimiter

error: could not compile `Number-Oracle` (bin "Number-Oracle") due to 1 previous error
}